### ISSUE TITLE
样式找不到

### ISSUE THREAD

**Issue by YYvue** [arco-design/arco-design-mobile#99]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-mobile/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/mobile-react@2.25.4

## Extra info
[vite] Internal server error: '~@arco-design/mobile-utils/style/mixin.less' wasn't found. Tried - /Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/@arco-design/mobile-react/tokens/mixin/~@arco-design/mobile-utils/style/mixin.less,node_modules/~@arco-design/mobile-utils/style/mixin.less,npm://~@arco-design/mobile-utils/style/mixin.less,~@arco-design/mobile-utils/style/mixin.less
  Plugin: vite:css
  File: /Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/@arco-design/mobile-react/tokens/mixin/index.less
  1  |  @import '~@arco-design/mobile-utils/style/mixin.less';
     |  ^
  2  |  @import './vars-switch.less';
  3  |  @import './pxtorem.less';
      at less (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:20596:33)
      at async compileCSS (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:20227:34)
      at async TransformContext.transform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:19876:50)
      at async Object.transform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29) (x2)

## What is expected?
[vite] Internal server error: '~@arco-design/mobile-utils/style/mixin.less' wasn't found. Tried - /Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/@arco-design/mobile-react/tokens/mixin/~@arco-design/mobile-utils/style/mixin.less,node_modules/~@arco-design/mobile-utils/style/mixin.less,npm://~@arco-design/mobile-utils/style/mixin.less,~@arco-design/mobile-utils/style/mixin.less
  Plugin: vite:css
  File: /Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/@arco-design/mobile-react/tokens/mixin/index.less
  1  |  @import '~@arco-design/mobile-utils/style/mixin.less';
     |  ^
  2  |  @import './vars-switch.less';
  3  |  @import './pxtorem.less';
      at less (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:20596:33)
      at async compileCSS (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:20227:34)
      at async TransformContext.transform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:19876:50)
      at async Object.transform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29) (x2)

## Steps to reproduce
[vite] Internal server error: '~@arco-design/mobile-utils/style/mixin.less' wasn't found. Tried - /Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/@arco-design/mobile-react/tokens/mixin/~@arco-design/mobile-utils/style/mixin.less,node_modules/~@arco-design/mobile-utils/style/mixin.less,npm://~@arco-design/mobile-utils/style/mixin.less,~@arco-design/mobile-utils/style/mixin.less
  Plugin: vite:css
  File: /Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/@arco-design/mobile-react/tokens/mixin/index.less
  1  |  @import '~@arco-design/mobile-utils/style/mixin.less';
     |  ^
  2  |  @import './vars-switch.less';
  3  |  @import './pxtorem.less';
      at less (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:20596:33)
      at async compileCSS (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:20227:34)
      at async TransformContext.transform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:19876:50)
      at async Object.transform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (/Users/yingdenghui/Documents/sihuo/YEX-web/newYex/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29) (x2)

**Comment by ChelesteWang** [comment]
可以参考这个 https://github.com/arco-design/arco-design-mobile/pull/68 处理一下

**Comment by supermars01** [comment]
> 可以参考这个 #68 处理一下

没看懂怎么解决
